jobs:
  - job: waitForValidation
    displayName: Wait for external Validation
    pool: server
    timeoutInMinutes: 4320
    steps:
    - task: ManualValidation@0
      timeoutInMinutes: 1440
      inputs:
        notifyUsers: |
          james.jones@rgp.com
          mark.tripp@rgp.com
        instructions: 'Please validate the build configuration and approve'
        onTimeout: 'reject'